# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.
# Docs: https://gohugo.io/content-management/menus/#define-in-site-configuration

main:
  - name: Home
    url: /#top
    weight: 10
  - name: About
    url: /#about
    weight: 20
  - name: Speakers
    url: /#speakers
    weight: 30
  - name: Agenda
    url: /#agenda
  - name: Contact
    url: https://www.newpush.com/contact-us/
    weight: 40

footer:
  - identifier: home
    name: Home
    weight: 1
  - parent: home
    name: Home
    url: /
    weight: 1
  - parent: home
    name: Contact
    url: https://www.newpush.com/contact-us/
  - identifier: tickets
    name: Tickets
    weight: 2
  - parent: tickets
    name: Get Tickets
    url: https://www.tixtree.com/e/25th-anniversary-symposium-artificial-intelligence-and-security-thriving-in-the-exponential-age-5e371b274895
  - parent: tickets
    name: Download Agenda
    url: /pdfs/Agenda_BAISS_NKE_ NOV_15_2024.pdf
    weight: 4
  - identifier: legal
    name: Legal
    weight: 3
  - parent: legal
    name: Privacy Statement
    url: /privacy
    weight: 1
  - parent: legal
    name: Terms and Conditions
    url: /terms
    weight: 2
