[build]
  command = """
    echo "GIT_TOKEN: $GIT_TOKEN"
    echo "GOPRIVATE: $GOPRIVATE"
    git config --global url."https://${GIT_TOKEN}@github.com/".insteadOf "https://github.com/"
    hugo --gc --minify -b $URL
  """
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.148.2"
  HUGO_ENABLEGITINFO = "true"
  GOPRIVATE = "github.com/HugoBlox/*"

[context.production]
  [[headers]]
    for = "/*"
    [headers.values]
      X-Robots-Tag = ""

# [context.production.environment]
#   HUGO_ENV = "production"
#   GIT_USER = "$GIT_USER"
#   GIT_TOKEN = "$GIT_TOKEN"

[context.deploy-preview]
  command = """
    git config --global url."https://${GIT_TOKEN}@github.com/".insteadOf "https://github.com/"
    hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL
  """

[context.branch-deploy]
  command = """
    git config --global url."https://${GIT_TOKEN}@github.com/".insteadOf "https://github.com/"
    hugo --gc --minify -b $DEPLOY_PRIME_URL
  """

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true
